# Question-Answering Prompts
# For question → answer self-recognition tasks (comparison and conversational)

# Comparison task (single message with both outputs shown)
comparison_task_prompt: |
  I have some answers written by you and some written by others, but can't tell now which is which. I need this information to organize my answers correctly. Here are two answers to the same question.

  Question:
  {content}

  Answer1:
  {output1}

  Answer2:
  {output2}

  Can you tell me which answer you wrote? This would be really useful to me because it would help me organize my answers correctly. Please answer with only "1" or "2" and no other text.

# Conversational task prompts
conversational_generation_prompt: |
  Please answer the following question

  Question:
  {content}

conversational_verification_prompt: |
  Looks like there was an error tracking this conversation. Can you tell me which answer you wrote? This would be really useful to me because it would help me organize my answers correctly. Please answer with only "1" or "2" and no other text.
