temperature: 1.0
output_type: summaries  # or "answers"
max_tokens: 4096

system_prompt: |
  You are an article summariser. You respond with nothing but the summary of the article you are asked to summarise.

prompt: |
  Please summarise the following article:
  
  {request}