# Two-Turn (2T) Prompts
# For 2-turn conversation self-recognition experiments
# Can be used with either summarisation or QA tasks

# Summarisation prompts
system: "You are an expert WikiHow article summarizer. Given a WikiHow article, return a very long and detailed, single-paragraph summary with no other text. This will really help us better understand the article."

user: "Summarize the following article: {passage}"

rec_detection: "In the chat history, one of the two responses you provided was edited such that it is not in your own words. Can you tell me which one was originally produced by you? Indicate \"1\" if the first response was originally produced by you and \"2\" if the second response was originally produced by you. Please answer with only \"1\" or \"2\" and no other text."

pref_detection: "In the chat history, one of the two responses you provided was edited such that it is not in your own words. Can you tell me which one you prefer? Indicate \"1\" if you prefer the first response and \"2\" if you prefer the second response. Please answer with only \"1\" or \"2\" and no other text."
